{% set version = '3.4.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xtractomatic
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/xtractomatic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xtractomatic/xtractomatic_{{ version }}.tar.gz
  sha256: 098dc26fdda15591645aa013550de24c0459717fe974d9fe71762b04cc9ce0f0

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-httr
    - r-ncdf4
    - r-readr
    - r-sp
  run:
    - r-base
    - r-dplyr
    - r-httr
    - r-ncdf4
    - r-readr
    - r-sp

test:
  commands:
    - $R -e "library('xtractomatic')"           # [not win]
    - "\"%R%\" -e \"library('xtractomatic')\""  # [win]

about:
  home: https://github.com/rmendels/xtractomatic
  license: CC0
  summary: Contains three functions that access environmental data from ERD's ERDDAP service
    <http://coastwatch.pfeg.noaa.gov/erddap>. The xtracto() function extracts data along
    a trajectory for a given "radius" around the point. The xtracto_3D() function extracts
    data in a box. The xtractogon() function extracts data in a polygon. There are also
    two helper functions to obtain information about available data, and plotting functions
    to plot the results.
  license_family: CC

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: xtractomatic
# Version: 3.4.2
# Title: Accessing Environmental Data from ERD's ERDDAP Server
# Authors@R: c( person("Roy", "Mendelssohn", email = "roy.mendelssohn@noaa.gov", role = c("aut","cre")), person("Cindy", "Bessey",  role = "ctb"), person("Dave", "Foley", role = "ctb"))
# Description: Contains three functions that access environmental data from ERD's ERDDAP service <http://coastwatch.pfeg.noaa.gov/erddap>. The xtracto() function extracts data along a trajectory for a given "radius" around the point. The xtracto_3D() function extracts data in a box. The xtractogon() function extracts data in a polygon. There are also two helper functions to obtain information about available data, and plotting functions to plot the results.
# Depends: R (>= 3.3.0)
# License: CC0
# LazyData: true
# URL: https://github.com/rmendels/xtractomatic
# BugReports: http://www.github.com/rmendels/xtractomatic/issues
# Imports: dplyr, httr, ncdf4, readr, sp, stats, utils
# Suggests: DT, ggplot2, knitr, lubridate, mapdata, reshape2, rmarkdown, webshot
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-03-12 21:01:09 UTC; rmendels
# Author: Roy Mendelssohn [aut, cre], Cindy Bessey [ctb], Dave Foley [ctb]
# Maintainer: Roy Mendelssohn <roy.mendelssohn@noaa.gov>
# Repository: CRAN
# Date/Publication: 2018-03-12 21:18:48 UTC
