appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Cba4jvHcKlnwvQhiC6iAd2OdvqxOa5qJQ1iqYX1PNo57mpMj9UfuV5cfUqzTHqkWPNjTRoc7KVPJ9hf95cIkAK7n/sQAg/h5Li1HlzEX1yOgFYIdncgoixzPuzH1w/71A56jPACZvSiiUt3y+bMt6APScoV37US8wUsNTaYUcA98NApZJ1I3DH4oRfQff/vwnPyytG9nxc1j8/2NemLpVYnjZQzkBYv7s7uuYwFsnNbG8eg7RJTjOG2ugERr+ezp+8GoK3K2GtH2FFMwOuGaqMA93DqR6kOmUVIgjB1WDbCYnQzmE2KdlsEz12QHB4dHDhIPYJ5mMYqHN6ibkQZir3yOLUqExNjEAGy4IqNTO2StlPuBmVaZ2EGBZbdyb7avlSAFcrpyjA2f4de6i/eYrX3e7kM+/HPcgdC03mZR1TIp6U8NzHL6m1+yctq2HHL34vHiTvxl0lRrQIZwW9dQaKjBrHJw5pQT5TX81175sQaMazSbKwQGkK2Ns8oCKsN2VmrKABen1UjUZUi+3vL/S7VemU4aUDYSqa6GnoGMXwEWKfCgd7wK084Dv2XAPcpEXIRfcC9Cbd4wwkWys4MR3oEtrBs2jFTXNnW2ElryELwO+TAO+jUAS0ec+TU9qYpQUgMxHoHi4y6IvjVz4JIGg31cO859GpoZfFTLjmV9xBI=}
bot:
  automerge: true
