travis:
  secure:
    BINSTAR_TOKEN: pdXiQVwErvRTEqnWuSHDZjj6lyjtQkl6nSsTayX5jp8ucReVyC8Ch4VcALaARTDWDPamgINfJPPz1MzS4l6p7cgSAr4sg2c5ewnQO/Pta2PMemMMjORBWzVA8LY2ipxhYMLJP/g4p2xbRJj9V/hMCRNZD5NuP8GGDLO2JxI1QxjGaiWpxerqkdZPBaYcY9NTtSicJvGsKv3jFp8uOXN0WRaVDm4b2xckdsUMbC0jUOSg8Y8jwl1NCJXj/zJpR03pUavNi5rA+dqA3ArRruW+DLLjftBuDR5Ds5VVfFHkCJBAZuqIPaODS61og1hq3yUgQbk8DWWrorRzumUqVgopu6AEvSqZd37zU1K8xCi+7xu04cFsvfiscWPx8DuJRnC+daLfz4dmZ6HTz/5earhdLQfcECDLssbAHrpqHv0AWtubOlCnnxxARf4ULMxWAO3Q/XLDZou3TXuVmqee9wiX/09xd1Cb55sYnB3Jda2eMQyTMzdXgva/nAdfsZvesEFEF17Te8kRMCjAL3i5JmGlUiHBQwlvignOQnSWXq7exZxuXVd6Lyi6FPoGGQ1GN+Dfr7tohMh8J38WqH9cIzW1rOrdi79bG7H9MpfRULv3LRvnRw4YgPO2LlLMoCS+OsvKzpzWZjIWUNLYX96ESUawMr2varSskF73MA32UMgyJqI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
